apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ecql2a2ad-go
  janus-idp.io/tekton: ecql2a2ad-go
  backstage.io/kubernetes-id: ecql2a2ad-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ecql2a2ad-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
