apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ecql2a2ad-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ecql2a2ad-go 
  name: ecql2a2ad-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ecql2a2ad-go 
